name: Hello-Numerical-World CI/CD

on:
  push:
    branches: ["CI-CD"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler:
          - { name: 'clang', version: '13' }
          - { name: 'clang', version: '14' }
          - { name: 'clang', version: '15' }
          - { name: 'gnu', version: '10' }
          - { name: 'gnu', version: '11' }
          - { name: 'gnu', version: '12' }

    steps:
    - uses: actions/checkout@v4

    - name: Set up compiler
      run: |
        sudo apt-get update
        if [ "${{ matrix.compiler.name }}" == "gnu" ]; then
          sudo apt-get install -y gcc-${{ matrix.compiler.version }} g++-${{ matrix.compiler.version }}
          export CC=gcc-${{ matrix.compiler.version }}
        elif [ "${{ matrix.compiler.name }}" == "clang" ]; then
          sudo apt-get install -y clang-${{ matrix.compiler.version }}
          export CC=clang-${{ matrix.compiler.version }}
        fi

    - name: make check
      run: 
        make check
